// Action Types de User
export const ACTION_AUTENTICACAO = 'ACTION_AUTENTICACAO';
export const ACTION_LOGIN = 'ACTION_LOGIN';

// Action Types de Wallet
export const ACTION_REQUEST = 'ACTION_REQUEST';
export const ACTION_RECEIVE = 'ACTION_RECEIVE';
export const ACTION_ADD_EXPENSE = 'ACTION_ADD_EXPENSE';
export const ACTION_REMOVE_EXPENSE = 'ACTION_REMOVE_EXPENSE';
export const ACTION_SELECT_EXPENSE = 'ACTION_SELECT_EXPENSE';
export const ACTION_EDIT_EXPENSE = 'ACTION_EDIT_EXPENSE';
