// Action Types de User
export const ACTION_EMAIL = 'ACTION_EMAIL';

// Action Types de Wallet
export const ACTION_REQUEST_START = 'ACTION_REQUEST_START';
export const ACTION_REQUEST_SUCCESS = 'ACTION_REQUEST_SUCCESS';
export const ACTION_REQUEST_FAIL = 'ACTION_REQUEST_FAIL';
export const ACTION_SAVE_EXPENSE = 'ACTION_SAVE_EXPENSE';
export const ACTION_DELETE_EXPENSE = 'ACTION_DELETE_EXPENSE';
export const ACTION_EDIT_EXPENSE_START = 'ACTION_EDIT_EXPENSE_START';
export const ACTION_EDIT_EXPENSE_END = 'ACTION_EDIT_EXPENSE_END';
